\* ZENTEC.MAC - for Zentec Zepher and Cobra *\
\*      to be used with AEDIT               *\
AV=24;
AFCU=0B; AFCD=0A; AFCR=0C; AFCL=08; AFCH=1E;
AFMU=0B; AFMD=0A; AFMR=0C; AFML=08; AFMH=1E;
AFES=1B 2B; AFER=1B 59; AFEK=0D 1B 54; AFEL=1B 54;
AFDL=1B 52; AFIL=1B 45;
AFAC=1B 3D; AO=20; AX=F;
AFRV=1B 47 34; AFNV=1B 47 30; AC=F; AI=F;
ADIL=60; \* 19200 baud *\

\* The DEL key (shift ESC) is used for <RUBOUT> *\
